language: objective-c

env:
  global:
    - LUAROCKS=2.2.1
  matrix:
    - LUA=lua5.1
    # - LUA=lua5.2
    # - LUA=lua5.3
    # - LUA=luajit
    # - LUA=luajit2.0
    # - LUA=luajit2.1

# os:
#   - linux
#   - osx

# branches:
#   only:
#     - master

before_install:
  - bash .travis/setup_lua.sh
  - sudo pip install cpp-coveralls
  - sudo luarocks install Lua-cURL         --server=https://rocks.moonscript.org/dev
  - sudo luarocks install luacov-coveralls --server=https://rocks.moonscript.org/dev
  - sudo luarocks install lunitx

install:
  - sudo luarocks make rockspecs/foo-scm-0.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-bundle -undefined dynamic_lookup -all_load --coverage"

script: 
  - cd test
  - lua -e "print(require'cURL'.version())"
  - lunit.sh test.lua

after_success:
  - coveralls -b .. -r .. --dump c.report.json
  - luacov-coveralls -j c.report.json -v

notifications:
  email:
    on_success: change
    on_failure: always
