language: objective-c

env:
  global:
    - PLATFORM=macosx
    - LUAROCKS_VER=2.1.0
    - LUAROCKS_BASE=luarocks-$LUAROCKS_VER
    - LUAROCKS_INSTALL=wget
    - LUAROCKS_GITTAG=master
    # - LUAROCKS_GITTAG=v$LUAROCKS_VER
  matrix:
    - LUA=lua5.1 LUA_SFX=    ZMQ_VER=libzmq
    - LUA=lua5.2 LUA_SFX=    ZMQ_VER=zeromq3
    - LUA=luajit LUA_SFX=jit ZMQ_VER=zeromq4

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - if [ "$ZMQ_VER" == "libzmq" ]; then
      bash .travis/setup_sodium.sh;
    fi
  - bash .travis/setup_zmq.sh

install:
  - sudo luarocks install lunitx
  - sudo luarocks install https://raw2.github.com/moteus/lzmq/master/rockspecs/lzmq-scm-0.rockspec
  - sudo luarocks make foo-scm-0.rockspec

script: 
  - lunit.sh -i lua$LUA_SFX test.lua
  - lua$LUA_SFX -llzmq -llzmq.timer -v

notifications:
  email:
    on_success: change
    on_failure: always
