language: erlang

env:
  global:
    - PLATFORM=linux
    - LUAROCKS_VER=2.1.0
  matrix:
    - LUA=lua5.1 LUA_SFX=
    - LUA=lua5.2 LUA_SFX=
    - LUA=luajit LUA_SFX=jit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh

install:
  - sudo luarocks install --server=http://rocks.moonscript.org lunitx
  - sudo luarocks make foo-scm-0.rockspec

script: 
  - cd test
  - lunit.sh -i lua$LUA_SFX test.lua

notifications:
  email:
    on_success: change
    on_failure: always
