language: objective-c

env:
  global:
    - LUAROCKS_VER=2.1.0
    - LUAROCKS_BASE=luarocks-$LUAROCKS_VER
    - LUAROCKS_INSTALL=wget
    - LUAROCKS_GITTAG=master
    # - LUAROCKS_GITTAG=v$LUAROCKS_VER
  matrix:
    - LUA=lua5.1 LUA_SFX=    ZMQ_VER=zeromq3
    - LUA=lua5.2 LUA_SFX=    ZMQ_VER=zeromq4
    - LUA=luajit LUA_SFX=jit ZMQ_VER=zeromq3

branches:
  only:
    - master

before_install:
  - bash .travis_setup.sh
  - git clone https://github.com/zeromq/$ZMQ_VER-x.git ./$ZMQ_VER;
  - cd ./$ZMQ_VER;
  - ./autogen.sh;
  - ./configure;
  - sudo make;
  - sudo make install;

install:
  - sudo luarocks install lunitx
  - sudo luarocks make foo-scm-0.rockspec

script: 
  - lunit.sh -i lua$LUA_SFX test.lua

notifications:
  email:
    on_success: change
    on_failure: always
